pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                Checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("myapp-test")
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    docker.image("myapp-test").inside {
                        sh "pytest"
                    }
                }
            }
        }

        stage('Deploy (Test Environment)') {
            steps {
                sh '''
                docker rm -f myapp || true
                docker run -d --name myapp myapp-test
                '''
            }
        }
    }

    post {
        success {
            echo 'pipeline executed successfully'
        }
        failure {
            echo 'pipeline failed'
        }
    }
}